[package]
name = "spellrs"
version = "0.1.0"
edition = "2021"
description = "Aliases some thematically appropriate code snippets to macros named after spells from Harry Potter, so that instead of calling drop(x), you can cast obliviate!(x)"
